### ISSUE TITLE
sbndaq_artdaq_core is missing c7 build on CVMFS

### ISSUE THREAD

**Issue by vitodb** [SBNSoftware/sbndaq-artdaq-core#11]
The CI runs a nightly build of ICARUS code uaing both e19 and c7 compiler qualifiers.
However the c7 build of sbndaq_artdaq_core is missing from CVMFS, this causes CI builds of ICARUS code stack to fail.

**Comment by wesketchum** [comment]
Now exists as of sbncode v09_08_00

**Comment by ikatza** [comment]
I don't see the `c7` builds either. Where in cvmfs are they @wesketchum?

More over, trying to build locally I'm getting an error saying that `c7` is not on the ups table.

**Comment by ikatza** [comment]
Was advised to use branch `offline` to build `c7` qual.
