### ISSUE TITLE
Build failure on OSX with anonymous union declaration

### ISSUE THREAD

**Issue by SFBayLaser** [SBNSoftware/sbndaq-artdaq-core#3]
Following error received:

[ 72%] Building CXX object sbndaq_artdaq_core/sbndaq-artdaq-core/Overlays/SBND/NevisTPC/CMakeFiles/sbndaq-artdaq-core_Overlays_SBND_NevisTPC.dir/NevisTPCTypes.cc.o
In file included from /LArSoft/ICARUS/development/sbndaq/build_d18.x86_64/workspace/temp/srcs/sbndaq_artdaq_core/sbndaq-artdaq-core/Overlays/SBND/NevisTPC/NevisTPCTypes.cc:1:
/LArSoft/ICARUS/development/sbndaq/build_d18.x86_64/workspace/temp/srcs/sbndaq_artdaq_core/sbndaq-artdaq-core/Overlays/SBND/NevisTPC/NevisTPCTypes.hh:24:5: error: anonymous types declared in an
      anonymous union are an extension [-Werror,-Wnested-anon-types]
    struct {
    ^
/LArSoft/ICARUS/development/sbndaq/build_d18.x86_64/workspace/temp/srcs/sbndaq_artdaq_core/sbndaq-artdaq-core/Overlays/SBND/NevisTPC/NevisTPCTypes.hh:44:5: error: anonymous types declared in an
      anonymous union are an extension [-Werror,-Wnested-anon-types]
    struct {
    ^
/LArSoft/ICARUS/development/sbndaq/build_d18.x86_64/workspace/temp/srcs/sbndaq_artdaq_core/sbndaq-artdaq-core/Overlays/SBND/NevisTPC/NevisTPCTypes.hh:58:5: error: anonymous types declared in an
      anonymous union are an extension [-Werror,-Wnested-anon-types]
    struct {
    ^
/LArSoft/ICARUS/development/sbndaq/build_d18.x86_64/workspace/temp/srcs/sbndaq_artdaq_core/sbndaq-artdaq-core/Overlays/SBND/NevisTPC/NevisTPCTypes.hh:72:5: error: anonymous types declared in an
      anonymous union are an extension [-Werror,-Wnested-anon-types]
    struct {
    ^
/LArSoft/ICARUS/development/sbndaq/build_d18.x86_64/workspace/temp/srcs/sbndaq_artdaq_core/sbndaq-artdaq-core/Overlays/SBND/NevisTPC/NevisTPCTypes.hh:86:5: error: anonymous types declared in an
      anonymous union are an extension [-Werror,-Wnested-anon-types]
    struct {
    ^
/LArSoft/ICARUS/development/sbndaq/build_d18.x86_64/workspace/temp/srcs/sbndaq_artdaq_core/sbndaq-artdaq-core/Overlays/SBND/NevisTPC/NevisTPCTypes.hh:100:5: error: anonymous types declared in an
      anonymous union are an extension [-Werror,-Wnested-anon-types]
    struct {
    ^
6 errors generated.

Will suppress with compiler flag for now but it seems clang would prefer the union declaration be named.

**Comment by wesketchum** [comment]
c7 builds now working.
